Structured base functions
jnandrawos/News_App pull request #7
Opened 2022-08-17 09:35 UTC by jnandrawos

Created Structured Base Functions for all activities and fragments

2022-08-21 10:50 UTC, joe-abouassi requested changes

2022-08-21 10:50 UTC, joe-abouassi commented on app/src/main/java/com/example/newsapp/ui/home/fragments/AboutUsFragment.kt
> +        setupView()
@jnandrawos can be moved to onViewCreated

2022-08-21 10:50 UTC, joe-abouassi commented on app/src/main/java/com/example/newsapp/ui/home/fragments/ArticleFragment.kt
> +        setupView()
@jnandrawos same comment

2022-08-21 10:50 UTC, joe-abouassi commented on app/src/main/java/com/example/newsapp/ui/home/fragments/ChangePasswordFragment.kt
> +        implementListeners()
@jnandrawos same

2022-08-21 10:50 UTC, joe-abouassi commented on app/src/main/java/com/example/newsapp/ui/home/fragments/EditProfileFragment.kt
> +        setupViews()
@jnandrawos same here

2022-08-22 12:03 UTC, jnandrawos commented on app/src/main/java/com/example/newsapp/ui/home/fragments/EditProfileFragment.kt
> +        setupViews()
done

2022-08-22 20:35 UTC, joe-abouassi approved these changes

2022-08-23 07:03 UTC, merged